# Generated by Django 5.2.5 on 2025-08-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_traking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
