# Generated by Django 5.2.5 on 2025-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_traking_app', '0003_alter_comment_author_alter_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
